name: PythonWebApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest


  Build_And_Push_Docker_Image:
    runs-on: ubuntu-latest
    needs: Test

    steps:
    - uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cptr9/pythonwebapp:2.0

    - name: Push Docker Image
      run: docker push cptr9/pythonwebapp:2.0

  Deploy_K8s:
    runs-on: ubuntu-latest
    needs: Build_And_Push_Docker_Image

    -name: Deploy to Kubernetes(using kubectl apply)
    run: |
      kubectl --kubeconfig k8s-kubeconfig.yaml apply -f k8s/deployment.yaml
      
