name: PythonWebApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: 2023mt03148@wilp.bits-pilani.ac.in
        password: Trace@Docker295

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cptr9/pythonwebapp:2.0

    - name: Push Docker Image
      run: docker push cptr9/pythonwebapp:2.0
